export const projects = [
  {
    id: "amazon-photo",
    title: "Amazon Photo",
    fullTitle: "FramePlay x Amazon Photos",
    description: "UGC per campagne pubblicitarie Amazon Photos",
    aspectRatio: "9/16",
    cover: "/Amazon/Amazon1.png",
    pic1: "/Amazon/Amazon1.png",
    pic2: "/Amazon/amazon2.png",
    pic3: "/Amazon/Amazon.png",
    par1: "Amazon Photos è un servizio di archiviazione online per foto e video. Offre un piano compreso nell'abbonamento di Amazon Prime.",
    par2: "Lo scopo delle campagne pubblicitarie di Amazon Photos era quello di far conoscere a quanta più gente possibile il suo servizio di storage online per foto e video compreso nell'abbonamento di Amazon Prime.",
    par3: "Il nostro lavoro è consistito nell'utilizzare i video RAW generati dagli utenti e trasformali in contenuti accattivanti e ad alto potenziale di conversione verso gli utenti in target con la campagna pubblicitaria. La sfida principale è stata quella di creare contenuti altamente coinvolgenti che, come scopo ultimo, avessero quello del donwload dell'applicazione",
  },
  {
    id: "promo-turismo-fvg",
    title: "Promo Turismo FVG",
    fullTitle: "FramePlay x PromoTurismoFVG",
    description: "Interviste agli atleti azzurri del Friuli Venezia Giulia",
    aspectRatio: "9/16",
    cover: "/Friuli/Friuli1.png",
    pic1: "/Friuli/Friuli1.png",
    pic2: "/Friuli/friuli2.png",
    pic3: "/Friuli/Friuli3.png",
    par1: "L'ente del turismo del Friuli Venezia Giulia è l’ente regionale che si occupa della strategia, della gestione operativa e della promozione turistica del Friuli Venezia Giulia, con al suo interno una divisione completamente dedicata al “food&wine”.",
    par2: "In occasione delle Olimpiadi di Parigi 2024 l'Ente del Turismo del Friuli Venezia Giulia ha ospitato un evento presso lo stadio Friuli dedicato alle eccelenze sportive del territorio. Durante questo evento 18 atleti hanno preso parte a delle rapide interviste incentrate sul territorio regionale.",
    par3: "Il nostro lavoro è consistito nel trasformare le interviste registrate durante l'evento e trasformarle in contenuti accattivanti e di qualità. Un ambiente non ottimizzato per questo tipo di interviste spesso può dimostrarsi ostico durante la fase di montaggio. Tramite color correction, audio enhancement e un serrato montaggio siamo riusciti a consegnare un prodotto di valore al cliente.",
    link: "https://www.instagram.com/reel/C6rOAwBN5rc/",
  },
  {
    id: "ale-della-giusta",
    title: "Ale della Giusta",
    fullTitle: "FramePlay x Ale della Giusta",
    description: "In viaggio per l'America con Rhove",
    aspectRatio: "16/9",
    cover: "/AleDellaGiusta/Aledellagiusta1.png",
    pic1: "/AleDellaGiusta/Aledellagiusta1.png",
    pic2: "/AleDellaGiusta/Aledellagiusta2.png",
    pic3: "/AleDellaGiusta/Aledellagiusta3.png",
    par1: "Ale della Giusta è un content creator italiano nonchè uno dei più grandi youtuber del nostro paese. Il suo canale youtube conta oltre 1 milione di follower e tutti i suoi video raggiungono oltre il mezzo milione di visualizzazioni.",
    par2: "Durante la sua serie dedicata al viaggio in America con Rhove, Ale ha deciso di affidarci l'incarico di montare una delle cinque puntate presenti in questa serie. Risultato che, con la supervisione di Alessandro Redaelli, ha raggiunto le quasi 700 mila visualizzazioni.",
    par3: "La sfida più grande di questo progetto è stata quella di trasformare le oltre 10 ore di registrato in poco più di 20 minuti di video finale. Per mantere sempre alta l'attenzione dello spettatore i contenuti di Ale della Giusta mantengono un ritmo incessante che rende il montaggio davvero laborioso.",
    link: "https://www.youtube.com/watch?v=LywaO_ixJes&t=39s",
  },
  {
    id: "spagnol",
    title: "Spagnol",
    fullTitle: "FramePlay x Spagnol",
    description: "Awareness sui social",
    aspectRatio: "9/16",
    cover: "/Spagnol/spagnol1.png",
    pic1: "/Spagnol/spagnol1.png",
    pic2: "/Spagnol/Spagnol2.png",
    pic3: "/Spagnol/Spagnol3.png",
    par1: "Spagnol SRL è una società specializzata nell'edilizia pubblica e privata, infrastrutture e costruzioni stradali con sede a Fiume Veneto.",
    par2: "L'azienda era desiderosa di far conoscere le proprie opere edili attraverso i social media decidendo di affidarci la creazione di video per aumentare il reach organico e pubblicitario. Pur partendo da un profilo creato da pochissimo tempo e pressoché privo di contenuti, i video sono riusciti a raggiungere migliaia di persone nel giro di poco tempo.",
    par3: "Grazie ai contenuti registrati dal cliente siamo riusciti a creare dei video accattivanti e strutturati appositamente per i social e per sottolineare la qualità del lavoro in maniera dinamica e accattivante utilizzando un linguaggio moderno.",
    link: "https://www.instagram.com/reel/C53GpXBMPDn/",
  },
  {
    id: "bertoja",
    title: "Bertoja",
    fullTitle: "FramePlay x Bertoja",
    description: "Awareness sui social",
    aspectRatio: "9/16",
    cover: "/Bertoja/Bertoja10.png",
    pic1: "/Bertoja/Bertoja10.png",
    pic2: "/Bertoja/Bertoja20.png",
    pic3: "/Bertoja/Bertoja30.png",
    par1: "Bertoja è un'azienda di Pordenone che progetta e produce una vasta gamma di semirimorchi e rimorchi ribassati e super ribassati per trasporti speciali",
    par2: "L'azienda era desiderosa di far conoscere i propri rimorchi attraverso i social media decidendo di affidarci la creazione di video per aumentare il reach organico e pubblicitario.",
    par3: "Grazie alle riprese video forniteci siamo stati in grado di generare dei contenuti video che abbracciassero la modernità dei social e che al contempo rispecchiassero a pieno i valori dell'azienda.",
    link: "https://www.instagram.com/reel/C6QjZWZCikb/",
  },
  {
    id: "hotel-san-michele",
    title: "Hotel San Michele",
    fullTitle: "FramePlay x Hotel San Michele",
    description: "Awareness sui social",
    aspectRatio: "9/16",
    cover: "/SanMichele/sanmichele10.png",
    pic1: "/SanMichele/sanmichele10.png",
    pic2: "/SanMichele/SanMichele20.png",
    pic3: "/SanMichele/SanMichele30.png",
    par1: "L'hotel San Michele di Bibione è un hotel 4 stelle con stanze a tema, piscina outdoor e la vicinanza al mare di Bibione",
    par2: "L'hotel ha deciso di utilizzare i social per far conoscere la propria struttura e poterne mostrare le sue invidiabili caratteristiche a chi ancora non le conosceva.",
    par3: "I social nell'ultimo periodo sono diventati uno strumento di marketing perfetto per la crescita organica, e non, degli hotel, motivo per il quale sempre più strutture decidono di buttarsi su Instagram e su TikTok. La sfida nella creazione dei video dedicati all'Hotel San Michele è stata quella di inventare creatività forti e uniche per accrescere la reputazione della struttura.",
    link: "https://www.instagram.com/reel/C7qm690N9AO/",
  },
  {
    id: "area-zenith",
    title: "Area Zenith",
    fullTitle: "FramePlay x Area Zenith",
    description: "Awareness sui social",
    aspectRatio: "9/16",
    cover: "/AreaZenith/Areazenith10.png",
    pic1: "/AreaZenith/Areazenith10.png",
    pic2: "/AreaZenith/Areazenith20.png",
    pic3: "/AreaZenith/areazenith30.png",
    par1: "Area Zenith è un ristorante di Bibione che offre esperienza di gusto unico, dal cornetto a colazione al drink del dopo cena.",
    par2: "Il ristorante ha cominciato a sfruttare la potenza dei social per comunicare la propria passione e ,in particolar modo, grazie all'utilizzo di foto di impatto e di video dinamici ha avviato la propria brand awareness su Instagram.",
    par3: "I social, e in particolar modo la comunicazione video, hanno un fortissimo impatto sulle strategie di marketing dei ristoranti. Catturare al meglio la qualità, l'attenzione al dettaglio e l'ambiente sono le sfide più ardue quando si vuole creare un video di valore.",
    link: "https://www.instagram.com/reel/C8OxXuMtaEt/",
  },
  {
    id: "eli-in-crimeland",
    title: "Eli in Crimeland",
    fullTitle: "FramePlay x Eli in Crimeland",
    description: "Editing video YouTube",
    aspectRatio: "16/9",
    cover: "/EliInCrimeland/EliinCrimeland.jpg",
    pic1: "/EliInCrimeland/EliinCrimeland.jpg",
    pic2: "/EliInCrimeland/EliinCrimeland2.png",
    pic3: "/EliInCrimeland/EliinCrimeland3.png",
    par1: "Eli in Crimeland è uno dei più grandi canali YouTube italiani che si occupa di True Crime.",
    par2: "Nel corso degli anni ci siamo occupati di realizzare diversi video per Elisa, risultato: oltre 20 milioni di visualizzazioni.",
    par3: "Non si tratta solamente di video ma di veri e propri documentari in cui mantenere alta l'attenzione dello spettatore e al contempo costruire un video che tocca argomenti cosi delicati è stata sicuramente la sfida principale di questo lavoro.",
    link: "https://www.youtube.com/watch?v=uzBrkgoAztg&t=1s",
  },
  {
    id: "ideal-glass",
    title: "Ideal Glass",
    fullTitle: "FramePlay x Ideal Glass",
    description: "Creazione video per advertising",
    aspectRatio: "4/5",
    cover: "/IdealGlass/idealglass.png",
    pic1: "/IdealGlass/Idealglass10.png",
    pic2: "/IdealGlass/Idealglass20.png",
    pic3: "/IdealGlass/idealglass30.png",
    par1: "IdealGlass è un'azienda di Forlì che si occupa della costruzione e del montaggio di vetrate panoramiche e molto altro",
    par2: "Il lavoro è consistito nel creare diversi video da utilizzare come advertising sulle piattaforme social in modo tale da permettere al brand di raggiungere nuovi potenziali clienti.",
    par3: "L'advertising è uno strumento utilizzato da ormai parecchio tempo da moltissime aziende ma l'advertising video è uno strumento che sta prendendo piede solamente nell'ultimo periodo motivo per il quale l'azienda ha deciso di affidare a noi i suoi lavori per poter creare contenuti di qualità. La sfida più grande di questo lavoro è rappresentata dal creare diverse creatives ad alta conversione in grado di portare quanti più lead qualificati al cliente.",
  },
  {
    id: "kube-fm",
    title: "KubeFm",
    fullTitle: "FramePlay x KubeFm",
    description: "Video interviste KubeCon 2024",
    aspectRatio: "16/9",
    cover: "/KubeFM/KubeFM10.png",
    pic1: "/KubeFM/KubeFM10.png",
    pic2: "/KubeFM/KubeFM20.png",
    pic3: "/KubeFM/KubeFM30.png",
    par1: "KukeFM è un podcast le cui puntate si basano sul raccontare, in maniera formativa, tutto ciò che avviene nel mondo di Kubernets.",
    par2: "Durante il KubeCon 2024 i ragazzi di KubeFM hanno prodotto svariate decine di interviste a vari amministratori o impiegati presso le più disparate aziende nel mondo di Kubernets, e si sono rivolti a noi per occuparci della parte del montaggio delle interviste.",
    par3: "Le interviste durante una fiera di questa portata rappresentano sempre una grande sfida perchè l'ambiente di registrazione non ottimale spesso risulta in audio non puliti. Grazie all'audio enhancement e ad un montaggio chirurgico siamo riusciti a dare vita ad interviste che hanno entusiasmato il cliente",
    link: "https://www.linkedin.com/posts/kubefm_abdelfettah-senior-developer-advocate-at-ugcPost-7193644417574998016-o39w?utm_source=share&utm_medium=member_desktop",
  },
  {
    id: "stratego-swat",
    title: "StrategoSwat",
    fullTitle: "FramePlay x StrategoSwat",
    description: "Creazione di video ADS e di contenuti organici",
    aspectRatio: "9/16",
    cover: "/Stratego/stratego.png",
    pic1: "/Stratego/Stratego10.png",
    pic2: "/Stratego/Stratego20.png",
    pic3: "/Stratego/Stratego30.png",
    par1: "StrategoSwat è una web agency che si occupa di SEO e di strategie di marketing.",
    par2: "Anche per le agenzie di marketing la comunicazione sta assumendo un ruolo sempre più centrale motivo per il quale StrategoSwat ha deciso di intraprendere un percordo di comunicazione tramite video per sé stessa e per i propri clienti.",
    par3: "I progetti svolti nel corso dei mesi per StrategoSwat sono stati molteplici e spaziavano dalla creazione di diverse video ADS fino ad arrivare alla creazione di contenuti studiati per l'organico.",
  },
  {
    id: "davvero-casa",
    title: "DavveroCasa",
    fullTitle: "FramePlay x DavveroCasa",
    description: "Realizzazione video per annunci immobiliari",
    aspectRatio: "16/9",
    cover: "/DavveroCasa/DavveroCasa1.png",
    pic1: "/DavveroCasa/DavveroCasa1.png",
    pic2: "/DavveroCasa/DavveroCasa2.png",
    pic3: "/DavveroCasa/DavveroCasa3.png",
    par1: "DavveroCasa è un'agenzia immobiliare che opera nei pressi di Como e ha alle spalle 30 anni di storia.",
    par2: "Il settore del Real Estate si sta spostando in massa verso la creazione dei contenuti video ma ciò che facciamo noi è portare lo standard di tali contenuti ad un livello superiore.",
    par3: "DavveroCasa, per il proprio sito, ci ha chiesto di realizzare alcuni contenuti interattivi per mostrare al meglio le qualità di svariati immobili del valore di centinaia di migliaia o milioni di euro.",
  },
  {
    id: "rosanna-lisco",
    title: "Rosanna Lisco",
    fullTitle: "FramePlay x Rosanna Lisco",
    description:
      "Creazione video verticali per i social e video per il sito web",
    aspectRatio: "16/9",
    cover: "/RosannaLisco/StudioLisco.png",
    pic1: "/RosannaLisco/RosannaLisco1.png",
    pic2: "/RosannaLisco/RosannaLisco2.png",
    pic3: "/RosannaLisco/RosannaLisco3.png",
    par1: "Rosanna Lisco è una consulente immobiliare nonchè titolare dello studio Rosanna Lisco",
    par2: "Rosanna è intenzionata ad utilizzare le potenzialità dei social per raggiungere nuovi potenziali clienti interessanti ad una valutazione del proprio immobile e al contempo aveva la necessità di realizzare dei contenuti esplicativi da poter inserire all'interno del suo sito web",
    par3: "La sfida di questo progetto è stata quella di creare contenuti unici che ponessero Rosanna come esperta dell'immobiliare di Torino mantenendo un tono autorevole e professionale ma al contempo dinamico e adatto ai social.",
  },
  {
    id: "endriu-files",
    title: "Endriu Files",
    fullTitle: "FramePlay x Endriu Files",
    description: "Editing video YouTube",
    aspectRatio: "16/9",
    cover: "/Endriu/Endriu1.png",
    pic1: "/Endriu/Endriu1.png",
    pic2: "/Endriu/Endriu2.png",
    pic3: "/Endriu/Endriu3.png",
    par1: "Endriu Files è uno dei più grandi canali YouTube italiani che si occupa di True Crime.",
    par2: "Nel corso degli ultimi mesi Endriu ha deciso di affidarci il montaggio dei suoi video che generano ogni settimana centinaia di migliaia di visualizzazioni.",
    par3: "Occuparsi del montaggio di veri e propri documentari True Crime rappresenta sempre un'ardua sfida, ma nonostante ciò siamo riusciti a produrre un contenuto che rispecchia a pieno i nostri standard di montaggio e che ha soddisfatto le richieste del cliente",
    link: "https://www.youtube.com/watch?v=3K4EX5lv7o4&t=4s",
  },
  // Add more projects as needed
];
